apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-alpha
  namespace: uat-alpha
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/sample-gateway

  http:
  - match:
    - uri:
        prefix: /alpha

    route:
    - destination:
        host: sample-app.uat-alpha.svc.cluster.local
        port:
          number: 80
      weight: 100

    headers:
      response:
        add:
          x-env: uat-alpha-v1
          x-test: jenkins-deploy
